import { Industry } from './industry';

export type Subindustry = {
    [key in keyof typeof industryMappings]: Industry;
};

export const industryMappings = {
    "Avtobusni prevozi": "Avtomobilizem",
    Avtodeli: "Avtomobilizem",
    "Avtodomi in prikolice": "Avtomobilizem",
    "Avtohiša in gospodarska vozila": "Avtomobilizem",
    Avtooprema: "Avtomobilizem",
    Avtopralnice: "Avtomobilizem",
    Avtoservis: "Avtomobilizem",
    Avtostoritve: "Avtomobilizem",
    Avtošola: "Avtomobilizem",
    "Bencinski servisi in kuriva": "Avtomobilizem",
    "Cestne storitve in oprema": "Avtomobilizem",
    "Dvigalne in transportne naprave": "Avtomobilizem",
    "Izposoja avtomobilov in motornih koles": "Avtomobilizem",
    "Motorji in oprema": "Avtomobilizem",
    Parkirišča: "Avtomobilizem",
    "Prevozništvo in transport": "Avtomobilizem",
    Taksi: "Avtomobilizem",
    "Tehnični pregledi": "Avtomobilizem",
    "Viličarji in tovorna vozila": "Avtomobilizem",
    "Vlečna služba": "Avtomobilizem",
    "Vodni promet": "Avtomobilizem",
    Vulkanizerstvo: "Avtomobilizem",
    "Železniški promet": "Avtomobilizem",
    "Alternativni viri energije": "Dom in vrt",
    "Arhitekturno in gradbeno načrtovanje": "Dom in vrt",
    "Barve, laki in kemični izdelki": "Dom in vrt",
    "Bazeni, masažne kadi in savne": "Dom in vrt",
    "Betonski in cementni izdelki": "Dom in vrt",
    Cvetličarna: "Dom in vrt",
    "Čistilnice in pralnice": "Dom in vrt",
    Čiščenje: "Dom in vrt",
    Domovi: "Dom in vrt",
    Ekologija: "Dom in vrt",
    Elektro: "Dom in vrt",
    Elektroinštalacije: "Dom in vrt",
    Energetika: "Dom in vrt",
    Fasaderstvo: "Dom in vrt",
    "Gasilstvo in protipožarna zaščita": "Dom in vrt",
    "Geodetske storitve": "Dom in vrt",
    "Gospodinjski aparati, izdelki in servis": "Dom in vrt",
    "Gradbena mehanizacija": "Dom in vrt",
    "Gradbeni material": "Dom in vrt",
    Gradbeništvo: "Dom in vrt",
    Izolacija: "Dom in vrt",
    Kamnoseštvo: "Dom in vrt",
    "Keramika in keramični izdelki": "Dom in vrt",
    "Klima in prezračevanje": "Dom in vrt",
    "Komunala in odpad": "Dom in vrt",
    "Komunalna infrastruktura": "Dom in vrt",
    "Montažne hiše": "Dom in vrt",
    Nepremičnine: "Dom in vrt",
    "Ogrevalna tehnika": "Dom in vrt",
    "Pohištvo in oprema": "Dom in vrt",
    Reciklaža: "Dom in vrt",
    "Selitveni servis": "Dom in vrt",
    Senčila: "Dom in vrt",
    Slikopleskarstvo: "Dom in vrt",
    "Stavbno pohištvo": "Dom in vrt",
    "Steklarstvo in stekleni izdelki": "Dom in vrt",
    Svetila: "Dom in vrt",
    "Šiviljstvo, krojaštvo in pletilstvo": "Dom in vrt",
    "Talne in stenske obloge": "Dom in vrt",
    Tapetništvo: "Dom in vrt",
    "Tekstil in tekstilni izdelki": "Dom in vrt",
    Vodoinštalacije: "Dom in vrt",
    "Vrtnarstvo in urejanje okolice": "Dom in vrt",
    "Vzdrževanje in upravljanje objektov": "Dom in vrt",
    "Zaključna dela v gradbeništvu": "Dom in vrt",
    Zidarstvo: "Dom in vrt",
    "Apartmaji in prenočišča": "Gostinstvo in turizem",
    Bar: "Gostinstvo in turizem",
    Catering: "Gostinstvo in turizem",
    "Dostava hrane": "Gostinstvo in turizem",
    "Gostilne in restavracije": "Gostinstvo in turizem",
    "Gostinska oprema": "Gostinstvo in turizem",
    "Hitra prehrana": "Gostinstvo in turizem",
    Hoteli: "Gostinstvo in turizem",
    Kampi: "Gostinstvo in turizem",
    "Kopališča in zdravilišča": "Gostinstvo in turizem",
    Letalstvo: "Gostinstvo in turizem",
    "Meso in mesni izdelki": "Gostinstvo in turizem",
    "Mleko in mlečni izdelki": "Gostinstvo in turizem",
    Navtika: "Gostinstvo in turizem",
    "Pekarstvo in slaščičarstvo": "Gostinstvo in turizem",
    "Picerije in špageterije": "Gostinstvo in turizem",
    Pijače: "Gostinstvo in turizem",
    "Prehrambena industrija": "Gostinstvo in turizem",
    "Turistične kmetije": "Gostinstvo in turizem",
    Turizem: "Gostinstvo in turizem",
    "Vinogradništvo in vinoteke": "Gostinstvo in turizem",
    "Izobraževalne institucije": "Izobraževanje in kultura",
    "Izobraževalni tečaji in inštrukcije": "Izobraževanje in kultura",
    "Kultura in umetnost": "Izobraževanje in kultura",
    "Muzeji in galerije": "Izobraževanje in kultura",
    "Tuji jeziki": "Izobraževanje in kultura",
    "Varstvo otrok": "Izobraževanje in kultura",
    "Čebelarstvo in medičarstvo": "Kmetijstvo",
    Gozdarstvo: "Kmetijstvo",
    "Kmetijski in gozdarski stroji": "Kmetijstvo",
    "Kmetijstvo, poljedelstvo in sadjarstvo": "Kmetijstvo",
    "Lesna dejavnost": "Kmetijstvo",
    "Ribištvo, ribogojstvo in ribarnica": "Kmetijstvo",
    "Alternativne oblike zdravljenja": "Lepota in zdravje",
    Farmacija: "Lepota in zdravje",
    "Frizerska dejavnost": "Lepota in zdravje",
    "Kozmetična dejavnost": "Lepota in zdravje",
    "Lekarne in specializirane trgovine": "Lepota in zdravje",
    "Manikura in pedikura": "Lepota in zdravje",
    "Medicinska in laboratorijska oprema": "Lepota in zdravje",
    "Nega telesa": "Lepota in zdravje",
    "Oblačila in modni dodatki": "Lepota in zdravje",
    "Obutev in čevljarstvo": "Lepota in zdravje",
    Optika: "Lepota in zdravje",
    "Oskrba na domu": "Lepota in zdravje",
    "Poroke in svečanosti": "Lepota in zdravje",
    "Zdravstveni in medicinski pripomočki": "Lepota in zdravje",
    Zdravstvo: "Lepota in zdravje",
    Zlatarstvo: "Lepota in zdravje",
    Zobozdravstvo: "Lepota in zdravje",
    "Aranžerstvo in dekoraterstvo": "Poslovni svet",
    Arhiviranje: "Poslovni svet",
    Banka: "Poslovni svet",
    "Biro oprema in servis": "Poslovni svet",
    Cenilstvo: "Poslovni svet",
    "Detektivska dejavnost": "Poslovni svet",
    Dimnikarstvo: "Poslovni svet",
    "Društvo, organizacija, združenje": "Poslovni svet",
    "Finančne storitve": "Poslovni svet",
    "Fotografske storitve in oprema": "Poslovni svet",
    "Fotokopiranje in drugo razmnoževanje": "Poslovni svet",
    "Grafične storitve in oblikovanje": "Poslovni svet",
    "Graverstvo, štampiljke in žigi": "Poslovni svet",
    "Invalidska podjetja": "Poslovni svet",
    "Javna uprava": "Poslovni svet",
    Knjigoveštvo: "Poslovni svet",
    "Kurirska služba": "Poslovni svet",
    Leasing: "Poslovni svet",
    "Marketing in oglaševanje": "Poslovni svet",
    "Merilni sistemi in naprave": "Poslovni svet",
    "Občine, upravne enote in lokalne skupnosti": "Poslovni svet",
    "Obdelava podatkov": "Poslovni svet",
    Pakiranje: "Poslovni svet",
    "Papirna galanterija": "Poslovni svet",
    "Podjetniške in poslovne storitve": "Poslovni svet",
    "Pogrebna dejavnost": "Poslovni svet",
    Pošta: "Poslovni svet",
    "Pravne storitve": "Poslovni svet",
    "Prevajanje, lektoriranje in tolmačenje": "Poslovni svet",
    Projektiranje: "Poslovni svet",
    "Računovodstvo in knjigovodstvo": "Poslovni svet",
    "Razstave, sejmi, kongresi": "Poslovni svet",
    "Reklamni in svetlobni napisi": "Poslovni svet",
    Revizija: "Poslovni svet",
    Skladišča: "Poslovni svet",
    "Spletna trgovina in prodaja po telefonu": "Poslovni svet",
    Tiskarstvo: "Poslovni svet",
    Trgovina: "Poslovni svet",
    "Varnostni sistemi in storitve": "Poslovni svet",
    "Varstvo pri delu": "Poslovni svet",
    "Veleposlaništvo, konzulat, predstavništvo": "Poslovni svet",
    Založništvo: "Poslovni svet",
    Zaposlovanje: "Poslovni svet",
    "Zavarovalne storitve": "Poslovni svet",
    Brusilstvo: "Proizvodnja in obrt",
    "Črpalke in kompresorji": "Proizvodnja in obrt",
    "Električni stroji in naprave": "Proizvodnja in obrt",
    Embalaža: "Proizvodnja in obrt",
    Galvanizacija: "Proizvodnja in obrt",
    Gumarstvo: "Proizvodnja in obrt",
    Hidravlika: "Proizvodnja in obrt",
    Ključavničarstvo: "Proizvodnja in obrt",
    Kovaštvo: "Proizvodnja in obrt",
    Kovinostrugarstvo: "Proizvodnja in obrt",
    "Kovinski izdelki in oprema": "Proizvodnja in obrt",
    "Krovstvo, kleparstvo in tesarstvo": "Proizvodnja in obrt",
    "Krznarstvo in usnjarstvo": "Proizvodnja in obrt",
    Livarstvo: "Proizvodnja in obrt",
    "Mehanika in finomehanika": "Proizvodnja in obrt",
    Mizarstvo: "Proizvodnja in obrt",
    "Okvirjanje slik": "Proizvodnja in obrt",
    Orodjarstvo: "Proizvodnja in obrt",
    "Orožje in strelivo": "Proizvodnja in obrt",
    Pečarstvo: "Proizvodnja in obrt",
    "Plastika in izdelki iz plastike": "Proizvodnja in obrt",
    "Prodajni avtomati": "Proizvodnja in obrt",
    "Rudnine in kamnine": "Proizvodnja in obrt",
    Svečarstvo: "Proizvodnja in obrt",
    Ščetarstvo: "Proizvodnja in obrt",
    Urarstvo: "Proizvodnja in obrt",
    "Antikvariati in starinarnice": "Prosti čas",
    "Astrologija in vedeževanje": "Prosti čas",
    "Darila, spominki in domača obrt": "Prosti čas",
    "Filmska in video dejavnost": "Prosti čas",
    "Fitnes in skupinske vadbe": "Prosti čas",
    Glasbeništvo: "Prosti čas",
    "Humanitarna in dobrodelna dejavnost": "Prosti čas",
    "Igrače in igralni pripomočki": "Prosti čas",
    "Igre na srečo": "Prosti čas",
    "Kino, gledališče in opera": "Prosti čas",
    "Knjigarne in papirnice": "Prosti čas",
    "Knjižnice in čitalnice": "Prosti čas",
    "Lov in lovske storitve": "Prosti čas",
    "Male živali": "Prosti čas",
    "Plesna šola": "Prosti čas",
    "Prireditvena dejavnost in zabava": "Prosti čas",
    "Radio in televizija": "Prosti čas",
    "Reja in prodaja živali": "Prosti čas",
    "Smučarski centri": "Prosti čas",
    "Šport in oprema": "Prosti čas",
    "Tobak in tobačni izdelki": "Prosti čas",
    "Verske organizacije in skupnosti": "Prosti čas",
    Veterinarstvo: "Prosti čas",
    Elektronika: "Računalništvo in informatika",
    "Mobilna telefonija": "Računalništvo in informatika",
    "Računalništvo in informatika": "Računalništvo in informatika",
    Telekomunikacije: "Računalništvo in informatika",
};
