name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_backend:
    name: Build backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install backend dependencies and build
        working-directory: backend
        run: |
          npm ci
          npm run build

  build_frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install frontend dependencies and build
        working-directory: frontend
        run: |
          npm ci
          npm run build
